name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.13.3
